version: "3.7"

services:
  database:
    image: postgres
    container_name: refresh_token_example
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=refresh_token_db
